### ISSUE TITLE
ANSI Encoding with Umlauts leads to compile errors and javadoc errors

### ISSUE THREAD

**Issue by HoffmannTom** [focus-shift/jollyday#108]
**Describe the bug**
When compiling with Java 17 I get errors due to encoding issues, e.g.:

```
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ jollyday-jaxb ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 44 source files to E:\EBS\jollyday-0.7.1\jollyday-jaxb\target\classes
[ERROR] /E:/EBS/jollyday-0.7.1/jollyday-jaxb/target/generated-sources/jaxb/de/focus_shift/jaxb/mapping/HolidayType.java:[4,4] unmappable character (0xC4) for encoding UTF-8
[ERROR] /E:/EBS/jollyday-0.7.1/jollyday-jaxb/target/generated-sources/jaxb/de/focus_shift/jaxb/mapping/HolidayType.java:[16,20] unmappable character (0xFC) for encoding UTF-8
```

The problems are the used Umlauts within the Java files.

**To Reproduce**
1) Download current release 0.7.1
2) Compile with Java 17 using the documented command

**Expected behavior**
Compile shouldn't fail.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win19
- Java 17 Coretto

**Additional context**
Similar problems occur when generating the javadocs. The Umlauts also causes errors.
Maybe converting everything to UTF-8 would be a good solution for the future or omit special characters.

**Comment by HoffmannTom** [comment]
hm... I updated to the same java version and also used git clone instead of downloading the zip file.
It looks like there are different default charactersets used.
Maybe it would be better to specify the charset of the source files via the parameter "-encoding" and thus being independent of the platform default.
[javadoc](https://docs.oracle.com/javase/9/javadoc/javadoc-command.htm)

**Comment by HoffmannTom** [comment]
Hello @derTobsch 
short update:
I changed the pom.xml with:
<project.build.sourceEncoding>Cp1252</project.build.sourceEncoding>

Currently there is UTF-8 configured.
When I clone the project, the Umlauts are ANSI encoded (single-byte) but UTF-8 is multibyte.
Could you check, whether your sources are UTF-8 or ANSI encoded?
Somehow there is currently a mismatch when I clone the repo.

Thanks!

**Comment by derTobsch** [comment]
Intellij says that everything is UTF-8 encoded. By builds are fine. This is also the preferred way to configure it, see https://maven.apache.org/plugins/maven-resources-plugin/examples/encoding.html. Need some time to look at it. Maybe you can take a look at your ide? Maybe there is something wrong? Or do you build it on a shell?

**Comment by HoffmannTom** [comment]
I think I got it
I changed the pom.xml within the jaxb folder:
```
              <jvmArguments>
                <jvmArgument>-Xms32m</jvmArgument>
				<jvmArgument>-Dfile.encoding=UTF-8</jvmArgument>
              </jvmArguments>
```

This worked for me.
