### ISSUE TITLE
Java 8 compatibility?

### ISSUE THREAD

**Issue by AngledLuffa** [focus-shift/jollyday#167]
Is it possible to get Java 8 compatibility for this module?  It would be useful to have a dropin replacement for the old Jollyday, which doesn't support Java 17 but does support Java 8.

Stanford CoreNLP uses Jollyday to detect holidays, but it apparently does not support Java 17:

https://github.com/svendiedrichsen/jollyday/issues/163

and some of our users are running into that issue:

https://github.com/stanfordnlp/CoreNLP/issues/1328

**Comment by grafjo** [comment]
@AngledLuffa I don't think so - Java 8 is way too old. The baseline is Java 11.

**Comment by AngledLuffa** [comment]
Fair enough.  Thanks for the response

**Comment by derTobsch** [comment]
Hey @AngledLuffa,

There will be no java 8 compatibility, we want to keep this lib up to date and moving. So baseline will be java 11.
