### ISSUE TITLE
com.sun.xml.bind dependency clashes with Spring Boot 3.0.1's org.glassfish.jaxb:jaxb-runtime:4.0.1

### ISSUE THREAD

**Issue by BernhardPosselt** [focus-shift/jollyday#173]
There have been some changes in the latest release that include org.glassfish.jaxb:jaxb-runtime; the dependencies of the jollyday jaxb version however include com.sun.xml.bind which breaks the gradle build with 

> Entry BOOT-INF/lib/jaxb-core-4.0.1.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

Fixed it with the following gradle dependency:

```kt
implementation("de.focus-shift:jollyday-jaxb:0.11.0") {
    exclude("com.sun.xml.bind", "jaxb-impl")
}
 ```

**Comment by derTobsch** [comment]
Thanks for your issue. I think we should switch to the glassfish dependency and be really close to spring boot 3.x.

**Comment by BernhardPosselt** [comment]
I'm not too deep into the whole Java tooling ecosystem with regards to that issue. Maybe it might make sense to not ship the runtime dependency and let the library consumer choose it themselves? Or at least document how you can swap out implementations in the README.

**Comment by derTobsch** [comment]
> I'm not too deep into the whole Java tooling ecosystem with regards to that issue. Maybe it might make sense to not ship the runtime dependency and let the library consumer choose it themselves? Or at least document how you can swap out implementations in the README.

Yes, I had the same ideas. I think we should go this way for now. And see where we are going.
