### ISSUE TITLE
denmark: General prayer day only until 2023

### ISSUE THREAD

**Issue by AndreasPetersen** [focus-shift/jollyday#187]
**Describe the bug**
The Holidays for Denmark are wrong: https://github.com/focus-shift/jollyday/blob/6d5b20dd13c32fae484f5251606baea3afc9b1a9/jollyday-core/src/main/resources/holidays/Holidays_dk.xml in version 0.12.0.

Christmas is described as December 25, but it is actually December 24. December 25 is Christmas Day, and December 26 is 2. Christmas day.

Also of note is that Great Prayer Day has been removed effective 2024: https://en.wikipedia.org/wiki/Store_Bededag

Please see:
https://www.visitaarhus.dk/aarhusregionen/planlaeg-din-tur/helligdage-i-danmark-gdk1101954
https://da.wikipedia.org/wiki/Danske_helligdage

**To Reproduce**

```
HolidayManager holidayManager = HolidayManager.getInstance(ManagerParameters.create(HolidayCalendar.DENMARK));
holidayManager.getHolidays(2023, "dk");
```

**Expected behavior**
The holidays should be correct

**Comment by derTobsch** [comment]
Thanks for your issue @AndreasPetersen,

as described here https://en.wikipedia.org/wiki/Public_holidays_in_Denmark the 24.12. is not a official public holiday. Is that correct? Same here https://github.com/nager/Nager.Date/blob/main/src/Nager.Date/PublicHolidays/DenmarkProvider.cs.

**Comment by AndreasPetersen** [comment]
Yeah, your absolutely correct @derTobsch , my apologies

**Comment by AndreasPetersen** [comment]
Isn't there still the following issues?
- names of the holidays on December 25 and 26 are incorrect. I can see that there is a first and second Christmas day name https://github.com/focus-shift/jollyday/blob/eb88454ca8f82a9e9f6fb62fa236e389a2a314e1/jollyday-core/src/main/resources/descriptions/holiday_descriptions.properties#L306-L307
- General prayer day is no longer starting next year (should have a `validTo="2023"` added)

**Comment by derTobsch** [comment]
If you want you can provide a pull request and improve the public holidays of Denmark. Of course you will get support from me.

**Comment by derTobsch** [comment]
Hey @AndreasPetersen,

I removed the general payers day starting from 2024.

I have no idea how I will continue with the translations in this lib. It is possible to add a new `holiday_descriptions_dk.properties` to provide all the translation needed. But on the other side, we need to add all translations for all public holidays provided by jollyday, even if this public holiday is not available in Denmark.

Maybe we should provide a global `holiday_descriptions.properties` with the English names of the public holidays for all holidays and provide specific `holiday_descriptions_dk.properties` that only overrides the public holidays in Denmark. What do you think?

**Comment by derTobsch** [comment]
I extracted the naming issue into #201 so we can fix the general prayer day in this issue

**Comment by AndreasPetersen** [comment]
Hi @derTobsch ,

Thank you for the effort, and apologies I haven't replied. I think it makes sense to extract the naming to a separate issue as done. I think you suggestion makes sense.
