### ISSUE TITLE
Add OSGi bundle manifest headers

### ISSUE THREAD

**Issue by wborn** [focus-shift/jollyday#254]
### More information

Would it be possible to add back the code for generating proper OSGi bundle manifest headers that got removed in https://github.com/focus-shift/jollyday/commit/f2404bb7c42659b83f918b42e6eef802967a7301?

Without these manifest headers it is less easy to use this library in OSGi based projects like [openHAB](https://www.openhab.org/).

**Comment by derTobsch** [comment]
Hey @wborn,

thanks for your issue. I will look into it. I removed a lot of code that "where just there" without any information why and who depends on it. It is nice to see a case to readd the module information.

**Comment by wborn** [comment]
Great!

Note that the commit removed support for 2 different modularity solutions.

All the bnd related config and bnd.bnd file is used for adding OSGi bundle headers to MANIFEST.MF in the JAR.

The module-info.java file is used by the Java Platform Module System (JPMS, aka project Jigsaw).

**Comment by derTobsch** [comment]
> Great!
> 
> Note that the commit removed support for 2 different modularity solutions.
> 
> All the bnd related config and bnd.bnd file is used for adding OSGi bundle headers to MANIFEST.MF in the JAR.
> 
> The module-info.java file is used by the Java Platform Module System (JPMS, aka project Jigsaw).

If you want to raise a pull request I am more than happy to look into it. At the moment I have no example project with OSGi to test against, so if you have one to offer, that would be awesome, because we need to add tests for the configuration.

**Comment by wborn** [comment]
OK I created https://github.com/focus-shift/jollyday/issues/254 for this.

It will probably be easier to integrate in openHAB when the Jackson support is added with  https://github.com/focus-shift/jollyday/pull/253. :slightly_smiling_face:

**Comment by derTobsch** [comment]
Hey @wborn,
there has been a failure on the release of 0.18.0 to maven central, but now https://github.com/focus-shift/jollyday/releases/tag/v0.19.0 is available.

**Comment by wborn** [comment]
Thanks! Looks like 1.19.1 made it to Maven Central. 👍
