### ISSUE TITLE
No Easter public holiday present in Czech republic

### ISSUE THREAD

**Issue by qck4fun** [focus-shift/jollyday#257]
### Affected country

Czech republic

### Affected public holiday

Easter

### Source of the information

https://en.wikipedia.org/wiki/Public_holidays_in_the_Czech_Republic

### More information

There is no such holiday as `Easter` in Czech republic - only `Good Friday` and `Easter Monday` and therefore function `isHoliday` returns wrong results.

![image](https://github.com/focus-shift/jollyday/assets/7276555/fbedbbf7-a79f-4bd1-b0d8-ef456a7a80da)

![image](https://github.com/focus-shift/jollyday/assets/7276555/73b5d32f-5c77-4e9e-ad69-cf75989f3fbc)

Removing this line from `Holidays_cz.xml` should do the trick:
```
<tns:ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
```

Or am I missing something?

**Comment by derTobsch** [comment]
> ### Affected country
> 
> Czech republic
> ### Affected public holiday
> 
> Easter
> ### Source of the information
> 
> https://en.wikipedia.org/wiki/Public_holidays_in_the_Czech_Republic
> ### More information
> 
> There is no such holiday as `Easter` in Czech republic - only `Good Friday` and `Easter Monday` and therefore function `isHoliday` returns wrong results.
> 
> ![image](https://user-images.githubusercontent.com/7276555/259180833-fbedbbf7-a79f-4bd1-b0d8-ef456a7a80da.png)
> 
> ![image](https://user-images.githubusercontent.com/7276555/259180681-73b5d32f-5c77-4e9e-ad69-cf75989f3fbc.png)
> 
> Removing this line from `Holidays_cz.xml` should do the trick:
> 
> ```
> <tns:ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
> ```
> 
> Or am I missing something?

Hey @qck4fun,

thanks for your issue! You are not missing anything, this is just wrong. I will fix this and release 0.19.0 today with this fix.
