### ISSUE TITLE
Breaking: make country codes ISO 3166 conformant

### ISSUE THREAD

**Issue by XSpielinbox** [focus-shift/jollyday#267]
### More information

Currently the list of countries largely uses the two letter codes as defined in ISO 3166-1 alpha-2.
The subdivisions also mostly use the codes defined in ISO 3166-2.

I hereby propose to unify this, that every subdivision adheres to this format.
So e.g. `gb.je` (Jersey) should be renamed to `gb.jsy`, `md.bti` should be renamed to `md.ba` (Bălți) and `in.dd` and `in.dn` should be merged to `in.dh` (Dādra and Nagar Haveli and Damān and Diu). [1]

As finer grained solutions for e.g. a certain city or township will be needed (e.g. for Assumption day), which will not be possible to do in a uniform way, wherefore I suggest to always put them behind the corresponding subdivision of ISO 3166-2. So e.g. `lu.clu` should be `lu.lu`, if it applies to the complete subdivision (Canton of Luxembourg). If it really only applies to its principal city, Luxembourg (more commonly known as Luxembourg City), it should then be something like `lu.lu.clu`. [2]

This would ensure consistency, prevent conflicts in the future and would make the codes easier to understand and amend/append.

[1]
* https://www.iso.org/obp/ui/#iso:code:3166:JE
* https://www.iso.org/obp/ui/#iso:code:3166:GB
* https://en.wikipedia.org/wiki/ISO_3166-2:JE
* https://en.wikipedia.org/wiki/ISO_3166-2:GB
* https://www.iso.org/obp/ui/#iso:code:3166:MD
* https://en.wikipedia.org/wiki/ISO_3166-2:MD
* https://www.iso.org/obp/ui/#iso:code:3166:IN
* https://en.wikipedia.org/wiki/ISO_3166-2:IN

[2]
* https://www.iso.org/obp/ui/#iso:code:3166:LU
* https://en.wikipedia.org/wiki/ISO_3166-2:LU

**Comment by derTobsch** [comment]
I really like the idea to be ISO 3166-2 conform (https://en.wikipedia.org/wiki/ISO_3166-2).

We should:
- provide information about the country and their available subdivision via api
- put wrongly grouped subdivisions in their own file (like jersey)
- ...

**Comment by derTobsch** [comment]
> ### More information
> 
> Currently the list of countries largely uses the two letter codes as defined in ISO 3166-1 alpha-2. The subdivisions also mostly use the codes defined in ISO 3166-2.
> 
> I hereby propose to unify this, that every subdivision adheres to this format. So e.g. `gb.je` (Jersey) should be renamed to `gb.jsy`, `md.bti` should be renamed to `md.ba` (Bălți) and `in.dd` and `in.dn` should be merged to `in.dh` (Dādra and Nagar Haveli and Damān and Diu). [1]
> 
> As finer grained solutions for e.g. a certain city or township will be needed (e.g. for Assumption day), which will not be possible to do in a uniform way, wherefore I suggest to always put them behind the corresponding subdivision of ISO 3166-2. So e.g. `lu.clu` should be `lu.lu`, if it applies to the complete subdivision (Canton of Luxembourg). If it really only applies to its principal city, Luxembourg (more commonly known as Luxembourg City), it should then be something like `lu.lu.clu`. [2]
> 
> This would ensure consistency, prevent conflicts in the future and would make the codes easier to understand and amend/append.
> 
> [1]
> 
>     * https://www.iso.org/obp/ui/#iso:code:3166:JE
> 
>     * https://www.iso.org/obp/ui/#iso:code:3166:GB
> 
>     * https://en.wikipedia.org/wiki/ISO_3166-2:JE
> 
>     * https://en.wikipedia.org/wiki/ISO_3166-2:GB
> 
>     * https://www.iso.org/obp/ui/#iso:code:3166:MD
> 
>     * https://en.wikipedia.org/wiki/ISO_3166-2:MD
> 
>     * https://www.iso.org/obp/ui/#iso:code:3166:IN
> 
>     * https://en.wikipedia.org/wiki/ISO_3166-2:IN
> 
> 
> [2]
> 
>     * https://www.iso.org/obp/ui/#iso:code:3166:LU
> 
>     * https://en.wikipedia.org/wiki/ISO_3166-2:LU

We go with exactly this approach. Thanks @XSpielinbox !
