### ISSUE TITLE
Assumption day is a holiday in most of bavaria

### ISSUE THREAD

**Issue by XSpielinbox** [focus-shift/jollyday#269]
### Affected country

Bavaria

### Affected public holiday

Assumption day

### Source of the information

https://www.statistik.bayern.de/mam/presse/2023/214_2023_44_a_mariae_himmelfahrt_2023.pdf

### More information

Additional source: https://www.statistik.bayern.de/statistik/gebiet_bevoelkerung/zensus/himmelfahrt/index.php

As Assumption day is a holiday in by far the most parts of Bavaria, in my opinion at least for now the default should change that all of Bavaria gets this holiday and there are exemptions for the few major cities that don't, in particular Ansbach, Schabach, Nürnberg, Fürth, Erlangen, Bayreuth, Coburg and Hof (cities listed with their German name).

**Comment by derTobsch** [comment]
Holidays that refer to a city we do not include it is now already very time-consuming to maintain everything.
