### ISSUE TITLE
Breaking: Move British Crown dependencies holidays to own files as they aren't part of Great Britain

### ISSUE THREAD

**Issue by XSpielinbox** [focus-shift/jollyday#270]
### More information

As Jersey has it's own country code `JE` now and isn't a subdivision of Great Britain, it should be moved outside of the definition `Holiday_gb.xml` into it's own `Holiday_je.xml`

`gb.jsy` (so `GB-JSY` respectively, see #267 ) should then be an alias for / redirect to `je` (so `JE` respectively), as it historically is the same territory or dropped completely.

Sources:
* https://www.iso.org/obp/ui/#iso:code:3166:JE
* https://www.iso.org/obp/ui/#iso:code:3166:GB
* https://en.wikipedia.org/wiki/ISO_3166-2:JE
* https://en.wikipedia.org/wiki/ISO_3166-2:GB
* https://www.britannica.com/story/whats-the-difference-between-great-britain-and-the-united-kingdom
* https://en.wikipedia.org/wiki/Crown_Dependencies
* https://en.wikipedia.org/wiki/Great_Britain
* https://en.wikipedia.org/wiki/United_Kingdom

The same applies to the Isle of Man and Guernsey, see:
* https://www.iso.org/obp/ui/#iso:code:3166:IM
* https://www.iso.org/obp/ui/#iso:code:3166:GG
* https://en.wikipedia.org/wiki/ISO_3166-2:IM
* https://en.wikipedia.org/wiki/ISO_3166-2:GG
* 
They all have been separated to there own country codes by ISO on 2007-04-17.

**Comment by derTobsch** [comment]
see also #267

**Comment by derTobsch** [comment]
> > Isn't it the same for:
> > ```
> > * Alderney (https://de.wikipedia.org/wiki/ISO_3166-2:GG)
> > 
> > * Guernsey (https://de.wikipedia.org/wiki/ISO_3166-2:GG)
> > 
> > * Isle of Man (https://de.wikipedia.org/wiki/ISO_3166-2:IM)
> > ``` 
> > ?
> 
> Yes, indeed.

Do you want to create two another issues that describe this for the other countries? And if you want, I would be more than happy if you create a pull request for this.

**Comment by derTobsch** [comment]
> > Do you want to create two another issues that describe this for the other countries? And if you want, I would be more than happy if you create a pull request for this.
> 
> In my opinion one could just adjust this issue, as it always affects GB and was changed at the same time. It therefore is the same underlying issue in my opinion.
> 

Lets do it in this issue and adapt the title and description.

> If you want separate issues, I can also create separate issues for that.
> 
> I can create a PR. I would have some questions on the implementation though:
> 
> Shall Jolliday just support the new codes or should the old codes be supported as well. In case the old codes should be supported too, how does one do that? I did not see a way to apply to apply one holiday.xml to a country-code and a subdivision of a different country code at the same time and duplicating all definitions seems like a really bad idea to me.
> 

I think it is ok to break in this case and only provide the new ones.

> Also I don't see an option to make a certain country-subdivision just a link to another country.
> 
> Or should all holidays in the time period before the change be tracked as the subdivision and all changes after that as the separate country? This would eliminate the need to do fancy symlinking or applying one definition to multiple codes, but would make it potentially more confusing and conflicting, if someone in the future accidentally breaks this distinction and adds holidays for the other time period to the wrong definition.
