### ISSUE TITLE
Add support for tns:MovingCondition in tns:IslamicHoliday

### ISSUE THREAD

**Issue by XSpielinbox** [focus-shift/jollyday#284]
### More information

Please enable to define child-elements of type `tns:MovingCondition` for elements of type `tns:IslamicHoliday`, as is possible with elements of type `fixed`.

This would make definition for e.g. the Hari Raya Haji and Hari Raya Puasa public holidays in Singapore (moved to the following Monday, if it would fall on a Sunday) way easier.

So, something like the following should be valid, what it is not at the moment:
```xml
<tns:IslamicHoliday type="ID_UL_ADHA_2" validFrom="2023" descriptionPropertiesKey="HARI_RAYA_HAJI">
    <tns:MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
</tns:IslamicHoliday>
```

see also https://www.mom.gov.sg/newsroom/press-replies/2008/rules-on-off-in-lieu

> Currently when a public holiday falls on a Sunday, the following Monday will be, by law, a holiday.

**Comment by derTobsch** [comment]
see #283
