### ISSUE TITLE
Bruderklausenfest missing in Oberwalden

### ISSUE THREAD

**Issue by XSpielinbox** [focus-shift/jollyday#369]
### Affected country

Swizerland - Obwalden

### Affected public holiday

Bruderklausenfest

### Source of the information

https://www.bj.admin.ch/dam/bj/de/data/publiservice/service/zivilprozessrecht/kant-feiertage.pdf.download.pdf/kant-feiertage.pdf
https://de.wikipedia.org/wiki/Feiertage_in_der_Schweiz
https://www.feiertagskalender.ch/index.php?geo=1604&jahr=2023&klasse=5&hl=de
https://www.seco.admin.ch/dam/seco/de/dokumente/Arbeit/Arbeitsbedingungen/Arbeitsgesetz%20und%20Verordnungen/Feiertage-Schweiz.pdf.download.pdf/Feiertage_2015_web_de.pdf

**Comment by derTobsch** [comment]
> Am 25. September, am Bruder-Klausen-Tag, der im Kanton Obwalden seit der Heiligsprechung 1947 Feiertag ist, ...
