### ISSUE TITLE
Error: Cannot instantiate datasource instance because there is no implementations

### ISSUE THREAD

**Issue by patrykbadowski12** [focus-shift/jollyday#398]
### More information

Hi. I have this one error when i try to use this jollyday-core.

`Exception in thread "main" java.lang.IllegalStateException: Cannot instantiate datasource instance because there is no implementations
	at de.focus_shift.jollyday.core.datasource.ConfigurationServiceManager.instantiateDataSource(ConfigurationServiceManager.java:33)
	at de.focus_shift.jollyday.core.datasource.ConfigurationServiceManager.getConfigurationService(ConfigurationServiceManager.java:22)
	at de.focus_shift.jollyday.core.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:43)
	at de.focus_shift.jollyday.core.caching.HolidayManagerValueHandler.createValue(HolidayManagerValueHandler.java:13)
	at de.focus_shift.jollyday.core.caching.Cache.lambda$get$0(Cache.java:27)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at de.focus_shift.jollyday.core.caching.Cache.get(Cache.java:27)
	at de.focus_shift.jollyday.core.HolidayManager.createManager(HolidayManager.java:105)
	at de.focus_shift.jollyday.core.HolidayManager.getInstance(HolidayManager.java:89)`

I am using with java 11.
`        <dependency>
            <groupId>de.focus-shift</groupId>
            <artifactId>jollyday-core</artifactId>
            <version>0.22.0</version>
        </dependency>`

Example code is just from documentation.
`        HolidayManager holidayManager = HolidayManager.getInstance(ManagerParameters.create(GERMANY));
        final Set<Holiday> holidays = holidayManager.getHolidays(2022);`
        
Can you help me resolve this problem ?

**Comment by derTobsch** [comment]
Did you also add the jaxb dependency?

**Comment by patrykbadowski12** [comment]
Yeah. It's kinda weird. 
In one test spring boot project it works without error.
I copied dependencies to another and trying to do the same and i have now
`WARN de.focus_shift.jollyday.core.support.LazyServiceLoaderCache - Cannot load services of type [de.focus_shift.jollyday.core.spi.ConfigurationService].
    de.focus_shift.jollyday.core.spi.ConfigurationService: Provider de.focus_shift.jollyday.jaxb.JaxbConfigurationService could not be instantiated`

**Comment by patrykbadowski12** [comment]
With 
`        <dependency>
            <groupId>de.focus-shift</groupId>
            <artifactId>jollyday-core</artifactId>
            <version>0.22.0</version>
        </dependency>
        <dependency>
            <groupId>de.focus-shift</groupId>
            <artifactId>jollyday-jaxb</artifactId>
            <version>0.22.0</version>
        </dependency>`

Now i have 
`Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/xml/bind/JAXBException`

**Comment by derTobsch** [comment]
do you have a `javax.xml.bind.*` on your classpath? If yes so need to add the jakarta jaxb dependency explicitly. I think that should be the error.

**Comment by patrykbadowski12** [comment]
I will close issue with little summary if somebody will need help.
With spring > 3.0 and java 17 this two dependencies are enough.
With spring < 3 and java 11 i added 
`        <dependency>
            <groupId>de.focus-shift</groupId>
            <artifactId>jollyday-jaxb</artifactId>
            <version>0.22.0</version>
        </dependency>
        <dependency>
            <groupId>de.focus-shift</groupId>
            <artifactId>jollyday-core</artifactId>
            <version>0.22.0</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>txw2</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.1.1</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.1</version>
        </dependency>`
And it works but you need to switch from javax to jakarta libraries in project.

**Comment by derTobsch** [comment]
> I will close issue with little summary if somebody will need help. With spring > 3.0 and java 17 this two dependencies are enough. With spring < 3 and java 11 i added
> 
> ```
>        <dependency>
>             <groupId>de.focus-shift</groupId>
>             <artifactId>jollyday-jaxb</artifactId>
>             <version>0.22.0</version>
>         </dependency>
>         <dependency>
>             <groupId>de.focus-shift</groupId>
>             <artifactId>jollyday-core</artifactId>
>             <version>0.22.0</version>
>         </dependency>
>         <dependency>
>             <groupId>org.glassfish.jaxb</groupId>
>             <artifactId>jaxb-core</artifactId>
>             <version>4.0.4</version>
>         </dependency>
>         <dependency>
>             <groupId>org.glassfish.jaxb</groupId>
>             <artifactId>jaxb-runtime</artifactId>
>             <version>4.0.4</version>
>         </dependency>
>         <dependency>
>             <groupId>org.glassfish.jaxb</groupId>
>             <artifactId>txw2</artifactId>
>             <version>4.0.4</version>
>         </dependency>
>         <dependency>
>             <groupId>jakarta.activation</groupId>
>             <artifactId>jakarta.activation-api</artifactId>
>             <version>2.1.2</version>
>         </dependency>
>         <dependency>
>             <groupId>jakarta.annotation</groupId>
>             <artifactId>jakarta.annotation-api</artifactId>
>             <version>2.1.1</version>
>         </dependency>
>         <dependency>
>             <groupId>jakarta.xml.bind</groupId>
>             <artifactId>jakarta.xml.bind-api</artifactId>
>             <version>4.0.1</version>
>         </dependency>
> ```
> 
> And it works but you need to switch from javax to jakarta libraries in project.

Yes, we only support the future with jakarta :)
