### ISSUE TITLE
Improve holiday types with bank holidays

### ISSUE THREAD

**Issue by derTobsch** [focus-shift/jollyday#462]
### More information

At the moment we have two holiday types. Official and Unofficial Holidays, but there are holiday in different countries that belong to e.g. Bank, School or Authorities Holidays. We want to improve the `HolidayTypes` Enum to represent this kind of holiday types.

At first we will add the possibility to add:
* Bank Holidays

**Comment by derTobsch** [comment]
> Could you describe the proposed changes meanings, please. Does the "School Holidays" represent when schools are closed? What's the purpose of "Authorities"?

I added a section in the readme on the branch. Is that sufficient?

**Comment by grekowski** [comment]
> I added a section in the readme on the branch. Is that sufficient?

You're sound man :+1:

**Comment by derTobsch** [comment]
> > I added a section in the readme on the branch. Is that sufficient?
> 
> You're sound man 👍

Did you took a look?


```
The following holiday types are supported:

| Type        | Description                                                                                                          |
|-------------|----------------------------------------------------------------------------------------------------------------------|
| Official    | Official public holiday                                                                                              |
| Bank        | Bank holiday, banks and offices are closed                                                                           |
| School      | School holiday, schools are closed                                                                                   |
| Authorities | Authorities are closed                                                                                               |
| Unofficial  | Unofficial holiday that is no <br/>Bank, School or Authorities holiday <br/>(Deprecated, please use the other types) |
```

**Comment by grekowski** [comment]
Just thinking, it might be very tricky with schools, as various types may have different timings, e.g. creche (kindergarten), primary, secondary, universities, etc... They all might have their own timings. For instance in Ireland all those types have different patterns. In Poland it goes by regions.

**Comment by derTobsch** [comment]
> Just thinking, it might be very tricky with schools, as various types may have different timings, e.g. creche (kindergarten), primary, secondary, universities, etc... They all might have their own timings. For instance in Ireland all those types have different patterns. In Poland it goes by regions.

Good objection, I think it would be enough for the start to only add `Bank` holidays additionally to `Official` and `Unofficial`

**Comment by derTobsch** [comment]
I thought about this. I think we need to do two things.
* Rename the 'official holiday' to 'public holiday', because this is what it is. see #482 
* Add bank holiday and provide the bank holidays for the specific countries. see #467

**Comment by derTobsch** [comment]
see #537 for more information
