### ISSUE TITLE
South Africa: 29 May - Public holiday (General Elections) missing 

### ISSUE THREAD

**Issue by benny-segwatlhe** [focus-shift/jollyday#523]
### Affected country

South Africa

### Affected public holiday

Public holiday (General Elections)

### Source of the information

https://www.gov.za/about-sa/public-holidays#*

### More information

Hi 

We have a national elections on the 29th of May 2024. 
That day has been declared a public holiday in the country.
My application is currently using the **jollyday version 0.5.7**

Could you please advise on what action to take.

Regards
Benny

**Comment by benny-segwatlhe** [comment]
Hey there @derTobsch 

Any ideas on this?

Regards
Benny

**Comment by derTobsch** [comment]
Hey @benny-segwatlhe,
the library that you use it not "the same" like this jollyday that has a different groupid. This library here is based in the one from sven diedrichsen, but is getting more and more different.

You need to change the gav to the one see information in the readme under https://github.com/focus-shift/jollyday?tab=readme-ov-file#xml-binding-libraries.

The election day you are describing is not supported at the moment and I had not the time to add it in the past. If you want you can add it in the following file https://github.com/focus-shift/jollyday/blob/main/jollyday-core/src/main/resources/holidays/Holidays_za.xml.
