### ISSUE TITLE
Thread safety, especially HolidayManager (?)

### ISSUE THREAD

**Issue by HoffmannTom** [focus-shift/jollyday#534]
### More information

Hello,
I haven't found any information about thread safety. My profiler shows, that e.g. HolidayManager.createManager() is quite time consuming.
Therefore, I would like to cache the instances per country / region.
Is this possible or are there any known multi-threading issues?
I don't know if HolidayManager is thread-safe.

If you have any information about thread-safety, I would be glad to know.

Thanks a lot!

**Comment by derTobsch** [comment]
Hey @HoffmannTom,

I would say yes the `HolidayManager` should be thread safe. We/I do create one `HolidayManager` per country and save them in a `HashMap` to access it later. We did not see any errors over the last years.

**Comment by HoffmannTom** [comment]
@derTobsch 
Thanks for the information!
