### ISSUE TITLE
Support additional holiday types - bank holidays and observance

### ISSUE THREAD

**Issue by kmcbride3** [focus-shift/jollyday#537]
### More information

Building on #482 and #462, which redefine 'official' holidays as 'public' holidays and introduce a new 'bank' holiday type respectively, a discussion should be had on what, if any, other holiday types should be considered for inclusion.

Assuming PR #467 goes through, Jollyday would support the following holiday types:
- **Public**: Public holiday
- **Bank**: Bank holiday, banks and offices are closed
- **Unofficial**: Holidays which are not public or bank holidays (Depreciated)

The original PR suggests types "Schools" (where schools are closed) and "Authorities" (where government offices/services are closed).

For consideration:
- **Observed**: Popular/common religious or cultural holidays where governments/businesses/schools normally do not close (such as April Fool's Day, Eid al-Adha, Diwali, St. Patrick's Day, Halloween, Yom Kippur in Canada)
- **Commemorative**: Not necessarily holidays, per se, but designated days to commemorate or recognize a person or event (such as International Women's Day, or in Canada, the Anniversary of the Statute of Westminster)

**Comment by derTobsch** [comment]
@kmcbride3 thanks for your input. I really appreciate it!

I would suggest the following

---

**Public**: Public holiday
Description: Public holidays are days when most of the public enjoys a non-working days. These days are determined by local laws and regulations. Countries use various names for these official non-working days, such as:

| Other Names for Public Holiday | Country          | Businesses |
|--------------------------------|------------------|------------|
| Bank Holiday                   | United Kingdom   | Closed     |
| National Holiday               | Most Countries   | Closed     |
| Red Days                       | Norway           | Closed     |
| Regular Holidays               | Philippines      | Closed     |
| Restricted Holidays            | India            | Closed     |
| Statutory Holiday              | Canada           | Closed     |

We will declare all of these as **Public Holiday**

**Bank**: Bank holiday, banks and offices are closed
Description: TODO

**Observance** Observance, is a celebration or commemoration that doesn't include a day off from work.
Description: When people celebrate or commemorate something, but do not have a day off from work for that reason, we call it an observance. 

There are different types of observance like Religious, Secular, Awareness, International or National observance. We will declare all of these as **Observance**

**Unofficial**: Holidays which are not public or bank holidays (Deprecated)
Description: Unofficial holidays are deprecated and will be replaced by the other types over time.


---

Maybe this types are enough to start and we can add more if we need them. Or are there must haves?

**Comment by derTobsch** [comment]
Hey @kmcbride3,
I updated the public holiday definition with _paid_ and also used your definition of bank holidays.

I would like to start without school holidays for the moment. We can add them later if we need them.

I thought the same about the naming of 'bank holidays' and I am not sure if there is a better "official" naming at the moment. I need to take a deeper look at that.

**Comment by kmcbride3** [comment]
Works for me, thank you for considering my feedback! I fully agree about the naming of 'bank holidays' - I couldn't think of a better name myself that would be more recognized/official.
