### ISSUE TITLE
Naefels Trip date is calculated wrong

### ISSUE THREAD

**Issue by 0x6e68** [focus-shift/jollyday#635]
### Affected country

Switzerland

### Affected public holiday

Naefels Trip 

### Source of the information

https://www.ferienwiki.ch/feiertage/naefelser-fahrt

### More information

At the moment, “Naefels Trip” is calculated as the second Thursday of April. This is incorrect because “Naefels Trip” is always on the first Thursday in April, except if it falls within “Karwoche” (“Holy Week”). In that case, it would be on the second Thursday of April.

You could reuse “FindWeekDayInMonth” but check if the date falls between (Easter - 7 days) and Easter. If that is the case, you could just add 7 days.

**Comment by derTobsch** [comment]
Hey @0x6e68,
thanks for your issue. I changed naefels to the first Thursday in April fix. And in the linked issue, I will take a look how I can provide the moving condition based on a week.
